name: Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: '[Prepare] Get Node.js version'
        id: node_version
        run: echo "version=$(cat package.json | jq -r .volta.node)" >> $GITHUB_OUTPUT
      - name: '[Prepare] Setup Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: ${{steps.node_version.outputs.version}}
          cache: 'npm'

      - name: Install dependencies
        uses: nick-fields/retry@v2
        with:
          command: npm ci
          timeout_minutes: 10
          max_attempts: 3

      - name: Echo env
        uses: nick-fields/retry@v2
        with:
          command: |
            echo $MY_ENV
            env
          timeout_minutes: 10
          max_attempts: 3
        env:
          MY_ENV: my_value

      - name: Run check
        run: npm run check:success
