name: simple

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: simple
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: echo
      run: echo "hello from simple action"
      
#    - name: Try to fail
#      run: exit 1
