name: manual

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      print_tags:
        description: 'True to print to STDOUT'
        required: true
        type: boolean
      tags:
        description: 'Test scenario tags'
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: echo $EVENT_CONTEXT
  print-tags:
    runs-on: ubuntu-latest
    if: ${{ inputs.print_tags }}
    steps:
      - name: Print the input tag to STDOUT
        run: echo The tags are ${{ inputs.tags }}
  print-secret:
    runs-on: ubuntu-latest
    steps:
      - env:
          CC_SECRET: ${{ secrets.CC_SECRET }}
        run: echo $CC_SECRET
      - name: print secret
        run: echo ${{ secrets.CC_SECRET }}
      - env:
          CC_SECRET2: ${{ secrets.CC_SECRET2 }}
        run: echo $CC_SECRET2
      - name: print secret2
        run: echo ${{ secrets.CC_SECRET2 }}