on:
  pull_request:
    types:
      - synchronize
      - opened
      - closed
name: preview
jobs:
  publish:
    if: (github.event.action == 'synchronize' || github.event.action == 'opened') && github.event.repository.fork == false
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Publish preview'
        run: npm run preview:publish
      - name: 'Debug'
        uses: actions/github-script@v6
        with:
          script: |
            console.log(context);

      - name: 'Add comment'
        if: github.event.action == 'opened'
        uses: actions/github-script@v6
        with:
          script: |
            console.log(context);
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.pull_request.number,
              body: `🔎 A preview has automatically been published at https://clever-components-preview.cellar-c2.services.clever-cloud.com/${context.pull_request.head.ref}/index.html. _This preview will be deleted once this PR is closed._`
            });
  delete:
    if: github.event.action == 'closed' && github.event.repository.fork == false
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Delete preview'
        run: npm run preview:delete
      - name: 'Add comment'
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.pull_request.number,
              body: `🔎 The preview has automatically deleted.`
            });
