on:
  pull_request:
    types:
      - synchronize
      - opened
      - closed
name: Preview
jobs:
  wait_for_build:
    name: 'Wait for build to succeed'
    if: |
      (github.event.action == 'synchronize' || github.event.action == 'opened') && 
      github.event.repository.fork == false && 
      !startsWith(github.event.pull_request.head.ref, 'release-please--')
    runs-on: ubuntu-latest
    steps:
      - name: 'Wait for build to succeed'
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          check-name: test
          ref: ${{ github.event.pull_request.head.sha }}
          allowed-conclusions: success
  publish:
    name: 'Publish Preview'
    needs: wait_for_build
    runs-on: ubuntu-latest
    steps:
      - name: '[Prepare] Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: '[Prepare] Get Node.js version'
        id: node_version
        run: echo "version=$(cat package.json | jq -r .volta.node)" >> $GITHUB_OUTPUT
      - name: '[Prepare] Setup Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: ${{steps.node_version.outputs.version}}
          cache: 'npm'
      - name: '[Prepare] Install dependencies'
        uses: nick-fields/retry@v2
        with:
          command: npm ci
          timeout_minutes: 10
          max_attempts: 3

      - name: '[Run] Publish preview'
        uses: nick-fields/retry@v2
        with:
          command: npm run preview:publish
          timeout_minutes: 10
          max_attempts: 3
        env:
          PREVIEWS_CELLAR_KEY_ID: ${{ secrets.PREVIEWS_CELLAR_KEY_ID }}
          PREVIEWS_CELLAR_SECRET_KEY: ${{ secrets.PREVIEWS_CELLAR_SECRET_KEY }}

      - name: '[Finalize] Add comment'
        if: github.event.action == 'opened'
        uses: actions/github-script@v6
        env:
          PREVIEW_BASE_URL: https://clever-components-preview.cellar-c2.services.clever-cloud.com
          BRANCH: ${{ github.event.pull_request.head.ref }}
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `🔎 A preview has been automatically published : ${process.env.PREVIEW_BASE_URL}/${process.env.BRANCH}/index.html.\n\n_This preview will be deleted once this PR is closed._`
            });
  delete:
    if: |
      github.event.action == 'closed' && 
      github.event.repository.fork == false &&
      !startsWith(github.event.pull_request.head.ref, 'release-please--')
    name: 'Delete Preview'
    runs-on: ubuntu-latest
    steps:
      - name: '[Prepare] Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: '[Prepare] Get Node.js version'
        id: node_version
        run: echo "version=$(cat package.json | jq -r .volta.node)" >> $GITHUB_OUTPUT
      - name: '[Prepare] Setup Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: ${{steps.node_version.outputs.version}}
          cache: 'npm'
      - name: '[Prepare] Install dependencies'
        uses: nick-fields/retry@v2
        with:
          command: npm ci
          timeout_minutes: 10
          max_attempts: 3

      - name: '[Run] Delete preview'
        uses: nick-fields/retry@v2
        with:
          command: npm run preview:delete
          timeout_minutes: 10
          max_attempts: 3
        env:
          PREVIEWS_CELLAR_KEY_ID: ${{ secrets.PREVIEWS_CELLAR_KEY_ID }}
          PREVIEWS_CELLAR_SECRET_KEY: ${{ secrets.PREVIEWS_CELLAR_SECRET_KEY }}

      - name: '[Finalize] Add comment'
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.issues.createComment({
             owner: context.repo.owner,
             repo: context.repo.repo,
             issue_number: context.issue.number,
              body: `🔎 The preview has been automatically deleted.`
            });
