on:
  workflow_run:
    workflows: ["Check"]
    types:
      - completed
name: preview2
jobs:
  publish:
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.repository.fork == false
    name: 'Publish Preview'
    runs-on: ubuntu-latest
    steps:
      - name: 'debug'
        run: echo ${{ github.event.workflow_run.pull_requests[0].number }}
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
          fetch-depth: 0

      - name: 'Publish preview'
        run: npm run preview:publish
      - name: 'Add comment'
        if: github.event.action == 'opened'
        uses: actions/github-script@v6
        env:
          PREVIEW_BASE_URL: https://clever-components-preview.cellar-c2.services.clever-cloud.com
          BRANCH: ${{ github.event.workflow_run.head_branch }}
          PR: ${{ github.event.workflow_run.pull_requests[0].number }}
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${process.env.PR},
              body: `🤖 🔎 A preview has been automatically published : ${process.env.PREVIEW_BASE_URL}/${process.env.BRANCH}/index.html.\n\n_This preview will be deleted once this PR is closed._`
            });
