name: publish-npm
on:
  push:
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]+'
      - '[0-9]+\.[0-9]+\.[0-9]+-alpha\.[0-9]+'
      - '[0-9]+\.[0-9]+\.[0-9]+-beta\.[0-9]+'
      - '[0-9]+\.[0-9]+\.[0-9]+-rc\.[0-9]+'
jobs:
  extract-npm-tag:
    runs-on: ubuntu-latest
    outputs:
      npm_tag: ${{ steps.extract_npm_tag.outputs.npm_tag }}
    steps:
      - name: Decode version from tag
        id: version_regex
        uses: actions-ecosystem/action-regex-match@v2
        with:
          text: ${{ github.ref_name }}
          regex: '^(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)(?:-([a-zA-Z]+)\.(?:0|[1-9]\d*))?$'
      - name: Extract npm tag from version
        id: extract_npm_tag
        if: ${{ steps.version_regex.outputs.match != '' }}
        shell: bash
        run: |
          TAG="latest"
          if [[ "${{ steps.version_regex.outputs.group1 }}" != "" ]]; then
            TAG="${{ steps.version_regex.outputs.group1 }}"
          fi
          echo "npm_tag=$TAG" >> $GITHUB_OUTPUT
  publish-npm:
    needs: extract-npm-tag
    if: ${{ needs.extract-npm-tag.outputs.npm_tag != '' }}
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        name: Publish version
        run: echo "Publish npm with tag '${{ needs.extract-npm-tag.outputs.npm_tag }}'"
