name: publish
on:
  push:
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]+'
      - '[0-9]+\.[0-9]+\.[0-9]+-alpha\.[0-9]+'
      - '[0-9]+\.[0-9]+\.[0-9]+-beta\.[0-9]+'
      - '[0-9]+\.[0-9]+\.[0-9]+-rc\.[0-9]+'
jobs:
  extract-npm-tag:
    runs-on: ubuntu-latest
    outputs:
      npm_tag: ${{ steps.extract_npm_tag.outputs.npm_tag }}
    steps:
      - name: Parse tag as SemVer
        id: parse_semver
        uses: booxmedialtd/ws-action-parse-semver@v1
        with:
          input_string: ${{ github.ref_name }}
        continue-on-error: true
      - name: Extract npm tag
        id: extract_npm_tag
        if: ${{ steps.parse_semver.outcome == 'success' }}
        shell: bash
        run: |
          TAG="latest"
          if [[ "${{ steps.parse_semver.outputs.prerelease }}" != "" ]]; then
            TAG="${{ steps.parse_semver.outputs.prerelease }}"
          fi
          echo "npm_tag=$TAG" >> $GITHUB_OUTPUT
      - if: ${{ steps.parse_semver.outcome == 'failure' }}
        name: Not a version tag... no publish
        run: echo "Not a version tag... no publish"
  publish-npm:
    needs: extract-npm-tag
    if: ${{ needs.extract-npm-tag.outputs.npm_tag != '' }}
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: echo "Publish npm with tag ${{ needs.extract-npm-tag.outputs.npm_tag }}"
