name: publish-npm
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v4
      - name: Extract branch name
        shell: bash
        run: echo "tag name = $GITHUB_REF_NAME"
