name: publish-npm
on:
  push:
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]+'
      - '[0-9]+\.[0-9]+\.[0-9]+-alpha\.[0-9]+'
      - '[0-9]+\.[0-9]+\.[0-9]+-beta\.[0-9]+'
      - '[0-9]+\.[0-9]+\.[0-9]+-rc\.[0-9]+'
jobs:
  pre-publish:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version_parse.outputs.version }}
      prerelease: ${{ steps.version_parse.outputs.prerelease }}
      release-needed: ${{ steps.version_parse.outputs.release-needed }}
    steps:
      - name: Decode version from tag
        id: version_regex
        uses: KyoriPowered/action-regex-match@v3
        with:
          text: ${{ github.ref_name }}
          regex: '^(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)(?:-([a-zA-Z]+)\.(?:0|[1-9]\d*))?$'
      - name: Parse version
        id: version_parse
        if: steps.version_regex.outputs.match != ''
        shell: bash
        run: |
          echo "prerelease=${{ steps.version_regex.outputs.group1 }}" >> $GITHUB_OUTPUT
          echo "version=${{ steps.version_regex.outputs.match != '' }}" >> $GITHUB_OUTPUT
          echo "release-needed=true" >> $GITHUB_OUTPUT
  publish-npm:
    needs: pre-publish
    if: needs.pre-publish.outputs.release-needed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Find NPM tag
        id: npm_tag
        run: p=${{ needs.pre-publish.outputs.prerelease }} && echo "tag=${p:-latest}" >> $GITHUB_OUTPUT
      - name: NPM - Publish version ${{ github.ref_name }} with tag ${{ steps.npm_tag.outputs.tag }}
        run: echo "[NPM] Publish version ${{ github.ref_name }} with tag ${{ steps.npm_tag.outputs.tag }}"
  publish-cdn:
    needs: pre-publish
    if: needs.pre-publish.outputs.release-needed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: CDN - Publish version ${{ github.ref_name }}
        run: echo "[CDN] Publish version ${{ github.ref_name }}"
